name: get git info

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  git_info:
    name: git info
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: display github
      run: |
        echo "${{ github.actor }}"
        echo "${{ github.ref }}"
        HEAD_REF=${{ github.head_ref }}
        REF=${{ github.ref }}
        echo "${HEAD_REF}$(echo ${REF##*/} | sed 's/merge//')"
