name: MegaLinter
on:
  pull_request:

jobs:
  MegaLinter:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: MegaLinter
        uses: oxsecurity/megalinter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
