name: Merge PR
on:
  pull_request:
    types: [closed] 
jobs:
  merge-PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: empty a.yaml
         run: |
           echo -e "" > a.yaml
      - name: commit a.yaml
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add a.yaml
           git commit -m 'cleaning a.yaml'
