name: Something
on:
  pull_request_review:
    types: [submitted] 
jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: display
        run: |
          echo "$GITHUB_CONTEXT"
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 

  merge-PR:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: empty a.yaml
        run: |
          echo -e "" > a.yaml

      - name: commit a.yaml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add a.yaml
          git commit -m 'cleaning a.yaml'
          git push
